### ISSUE TITLE
MUNBYN IPDA053 with 2D QR Zebra SE4710 Reader

### ISSUE THREAD

**Issue by cmnstmntmn** [darryncampbell/DataWedgeReactNative#11]
Hei,

I'm having this handheld running Android 7.1.2, and i can't make it work.

I've build [DataWedgeReactNative](https://github.com/darryncampbell/DataWedgeReactNative) on the device, and this is the screen i've have:

![Screenshot_20200511-165901](https://user-images.githubusercontent.com/2312755/81611450-bca4d600-93e3-11ea-8554-dc3c5aeef322.png)

the Scanner settings looks like this

![Screenshot_20200511-165939](https://user-images.githubusercontent.com/2312755/81611470-c75f6b00-93e3-11ea-9114-7eb0e5f0ec41.png)

thank you in advance

**Comment by darryncampbell** [comment]
Hi, what device are you using?

**Comment by cmnstmntmn** [comment]
@darryncampbell it's MUNBYN IPDA053

**Comment by darryncampbell** [comment]
Thank you for clarifying.
This application was designed to work with Zebra Android devices.  Although the SE4710 is a Zebra scanner the DataWedge application is not available on MUNBYN devices.  There may be something similar (as you show in your second screenshot) but I have never tried it on a non-Zebra device as the application was written assuming a DataWedge interface.

**Comment by cmnstmntmn** [comment]
i see, thank you @darryncampbell
