### ISSUE TITLE
DS9208 Connection issue

### ISSUE THREAD

**Issue by fahadibrahimbutt** [darryncampbell/DataWedgeReactNative#15]
Can this code communicate with DS9208  scanner model as well?

**Comment by darryncampbell** [comment]
I don't think DataWedge supports the DS9208 does it?  Please see the supported list at https://techdocs.zebra.com/datawedge/8-1/guide/input/barcode/, so I think the answer is no I'm afraid.

**Comment by fahadibrahimbutt** [comment]
I just use Zebra **'Scanner Control'** ### https://play.google.com/store/apps/details?id=com.zebra.scannercontrol.app&hl=en App.
And this Model (DS9208) works for me.

@darryncampbell 
This model is not mentioned in the supported list but is working fine.
