### ISSUE TITLE
Reloading and double scan problem

### ISSUE THREAD

**Issue by sergeykotor** [darryncampbell/DataWedgeReactNative#20]
**Hello!** 
In the debug mode, when scanning the date matrix codes, it is reloaded. There is also the problem of double scanning, when the scanner does not go into disabled mode immediately, but only after the second scan. And if it turns out to be scanned once, then two entries are displayed in the console. React version 0.63, device TC70

**Comment by darryncampbell** [comment]
Hi, taking these one at a time, what are the reproduction steps for the reload issue?  I don't have a TC70 but I install this app on another Zebra device and it seems to scan OK, at least using the physical trigger (the software button will emit the scanner beam after you release it which is a bit disorientating at first).  This is also using React native version 0.63.3

**Comment by sergeykotor** [comment]
> Привет, беря их по одному, каковы шаги воспроизведения для решения проблемы перезагрузки? У меня нет TC70, но я устанавливаю это приложение на другое устройство Zebra, и оно, кажется, сканирует нормально, по крайней мере, с помощью физического триггера (программная кнопка будет излучать луч сканера после того, как вы отпустите его, что сначала немного дезориентирует) . Здесь также используется собственная версия React 0.63.3.

Sorry, I wrote in the wrong place
https://github.com/darryncampbell/react-native-datawedge-intents/issues/13

**Comment by darryncampbell** [comment]
No worries, I will close this ticket and reply in darryncampbell/react-native-datawedge-intents#13
