### ISSUE TITLE
How to print scanner output?

### ISSUE THREAD

**Issue by dreamchasersuon** [darryncampbell/DataWedgeReactNative#3]
Hello! I have a question regarding this implementation. Specifically about printing scanned barcode. If I use your example app, and after START_SCANNING method I receive an object which don't have 'com.symbol.datawedge.data_string' and another options. How to print output from the scanner?

**Comment by darryncampbell** [comment]
Hi, which device are you using?

**Comment by dreamchasersuon** [comment]
Zebra MC330M.

**Comment by darryncampbell** [comment]
Unfortunately I do not have that device to try it out.  Your device should look similar to the screenshot in the ReadMe file and I also suggest ensuring the DataWedge profile has been created successfully (see the Setup section in the readme).  You should see the scanned barcode output to the console from https://github.com/darryncampbell/DataWedgeReactNative/blob/master/App.js#L258 .  To answer your question about printing output from the scanner, you may want to take a look at the React Native Debugging documentation: https://facebook.github.io/react-native/docs/debugging

**Comment by dreamchasersuon** [comment]
BTW, all works just fine. The only problem that I can't print resulting barcode in the application.
After triggering 'Soft_Scan_Trigger' method I discovered that code stopped working in broadcastReceiver at this line:

`else if (!intent.hasOwnProperty('RESULT_INFO')) { // A barcode has been scanned this.barcodeScanned(intent, new Date().toLocaleString()); }`

I replace the following expression with another one to trigger: 
`this.barcodeScanned(intent, new Date().toLocaleString());.`

Unfortunately, I received the:
 `Object { "COMMAND": "com.symbol.datawedge.api.SOFT_SCAN_TRIGGER", "RESULT": "SUCCESS", "RESULT_INFO": Object { "PROFILE_NAME": "ZebraReactNativeDemo", }, "v2API": true, }`, from which I can't select barcode data...

**Comment by darryncampbell** [comment]
Pressing the yellow "scan" button in the app UI should have the same effect as pressing the yellow hardware trigger on the device.  Both should show scanned data within blue bubbles.  Are you saying that ONLY the hardware trigger successfully shows scanned data within the blue bubbles?

**Comment by dreamchasersuon** [comment]
No, when I pressed the application yellow button it fires in console with: 
`Object { "COMMAND": "com.symbol.datawedge.api.SOFT_SCAN_TRIGGER", "RESULT": "SUCCESS", "RESULT_INFO": Object { "PROFILE_NAME": "ZebraReactNativeDemo", }, "v2API": true, }`. But no results if I triggering the hardware button. 

So, the same result in both cases. The difference is that hardware button don't print the output in the console.

**Comment by dreamchasersuon** [comment]
The profile configured successful, and I can fire/receive intents. But when I press the 'scan' button it outputs with this object, and I can't extract the barcode data from this object because they don't exist inside it.

**Comment by dreamchasersuon** [comment]
As I understand, this method `this.sendCommand("com.symbol.datawedge.api.SOFT_SCAN_TRIGGER", 'TOGGLE_SCANNING');` should resulting with this values: `com.symbol.datawedge.data_string` and `com.symbol.datawedge.label_type`. 

But it returns me this `Object { "COMMAND": "com.symbol.datawedge.api.SOFT_SCAN_TRIGGER", "RESULT": "SUCCESS", "RESULT_INFO": Object { "PROFILE_NAME": "ZebraReactNativeDemo", }, "v2API": true, }`.

Where can I did a mistake?

**Comment by darryncampbell** [comment]
That message is being returned to indicate that SOFT_SCAN_TRIGGER was processed successfully, it does not contain scan data.  Please restore DataWedge back to default settings (http://techdocs.zebra.com/datawedge/7-2/guide/settings/#restoredefaults) and try running the application again - pressing the soft yellow 'Scan' button should result in the scanner beam emitting and after a barcode is scanned your application will receive a scan object via Broadcast Receiver.

**Comment by dreamchasersuon** [comment]
Thanks! It solved the issue.

**Comment by darryncampbell** [comment]
Great. I'm not sure why a reset was required but glad it's working now
