### ISSUE TITLE
Using Camera Scanner

### ISSUE THREAD

**Issue by goyanx** [darryncampbell/DataWedgeReactNative#36]
Is there a way to use the camera scanner of the device ?

**Comment by darryncampbell** [comment]
Hi, yes, you need to select the Camera Scanner from the DataWedge Profile, under Scanner Selection.  More information is here: https://techdocs.zebra.com/datawedge/8-2/guide/input/barcode/#scannerselection

**Comment by goyanx** [comment]
I see what you mean. However programmatically is there also a way to set the camera scanner to default ? Or Scanner Selection is the only way ? Thanks!

**Comment by darryncampbell** [comment]
Yes, please use scanner_selection_by_identifier with "INTERNAL_CAMERA".  https://techdocs.zebra.com/datawedge/8-2/guide/api/setconfig/

**Comment by goyanx** [comment]
Thanks!
