### ISSUE TITLE
Work with Nativescript?

### ISSUE THREAD

**Issue by RayburnTrading** [darryncampbell/DataWedgeReactNative#4]
Would it be possible for this plugin to work with Nativescript?

Or can you point me in the direction of a solution?

**Comment by darryncampbell** [comment]
No, it is not possible to use this plugin with NativeScript as ReactNative plugins and NativeScript plugins are not cross compatible.

You should be able to achieve this without any plugins however, I notice NativeScript has support for Intents through the Application class: https://docs.nativescript.org/ns-framework-modules/application which should enable you to register a broadcast receiver to receive scan data.

**Comment by RayburnTrading** [comment]
Ah, you're right thanks for the pointer.
