### ISSUE TITLE
Is working for ios ?

### ISSUE THREAD

**Issue by vishal-gtl** [darryncampbell/DataWedgeReactNative#6]
I have zebra(CS4070) barcode scanner device and i want to integrate with my react-native cross platform app for Android & ios. 

In this demo i found only android code so can you suggest how to integrate for both platform Android & ios.

Is there any other way ?

Thanks in advance.

**Comment by darryncampbell** [comment]
This project does not support the CS4070 even on Android - you could either create a native plugin using the scanner SDKs for Android & iOS: https://www.zebra.com/us/en/support-downloads/scanners/companion-scanners/cs4070.html or it may be easier to put the scanner into HID mode and just capturing the keystrokes.  You can put the scanner into HID mode by modifying the configuration file, see the product reference guide section 1-9 at the link I specified above.
