### ISSUE TITLE
ReactNative + RFID

### ISSUE THREAD

**Issue by saymoncoppi** [darryncampbell/DataWedgeReactNative#7]
Hello Darryl!
We are wondering to convert an C# app to Reactive Native. I saw your repository and decided to ask you about rfid projects using this technology.

Do you have some thoughts for this subject?
Tks

**Comment by darryncampbell** [comment]
Hi, I should warn you I may not be the best person to ask but I can try... which RFID devices are you using?

**Comment by saymoncoppi** [comment]
Hello Buddy sorry this delay... RFD2000 and RFD8500 with TC2X

**Comment by darryncampbell** [comment]
You would need to write a plugin to interface to the native SDK I think, the links to the RFID SDKs are at https://www.zebra.com/us/en/support-downloads/rfid/rfid-handhelds/rfd2000.html and https://www.zebra.com/us/en/support-downloads/rfid/rfid-handhelds/rfd-8500.html

**Comment by saymoncoppi** [comment]
Tks

Em qua, 9 de out de 2019 12:43, Darryn <notifications@github.com> escreveu:
