### ISSUE TITLE
Use Scanner Keyboard

### ISSUE THREAD

**Issue by akrueger90** [darryncampbell/DataWedgeReactNative#9]
Hello, 

I know it does not belong directly to this project. 

Is there a way to use the Keyboard (for example on the MC33) correctly? By default it is not possible to switch the letters. 

Kind regards

**Comment by darryncampbell** [comment]
Hi, I'm not sure I understand the question, what do you mean by 'switch the letters'?  Please post your answer to developer.zebra.com and I will try to help there, thanks.
